Traceback (most recent call last):
  File "/Users/macos/repos/google-it-automation/interact-with-os/6_Bash_Scripting/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR: ")
ValueError: Now we generate an error to STDERR: 
